server:
    port: 8080
spring:
    application:
        name: employee service
    datasource:
        driver-class-name: org.h2.Driver
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 100
            pool-name: EmployeePool
        url: jdbc:h2:file:~/spring-boot-h2-db
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: update
springdoc:
    swagger-ui:
        path: /
